### ISSUE TITLE
Pa[sss]word  src/index.ts#L243

### ISSUE THREAD

**Issue by Aetherall** [js-accounts/mongo#27]
https://github.com/js-accounts/mongo/blob/911e8f06ce2d77dc1d7775f7808493dd64773fed/src/index.ts#L243

**Comment by Aetherall** [comment]
https://github.com/js-accounts/mongo/blob/911e8f06ce2d77dc1d7775f7808493dd64773fed/src/index.ts#L404

**Comment by davidyaha** [comment]
Thanks @Aetherall!
